version: "3.9"
services:
    database:
        image: mysql
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_DATABASE: "api-database"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes: 
            - "./src/database/mysql:/var/lib/mysql"
        ports:
            - "3306:3306"
    api:
        build: "./"
        container_name: node_container
        volumes: 
            - "./:/usr/app"
        restart: always
        ports:
            - "3030:3030"
        depends_on: 
            - database
